##### Menu
menu:
  首页: /
  归档: /archives
  关于: /about
## you can create `tags` and `categories` folders in `../source`.
## And create a `index.md` file in each of them.
## set `front-matter`as
## layout: tags (or categories)
## title: tags (or categories)
## ---

#### Widgets
widgets: 
- category
- links
## provide seven widgets:category,tag,rss,archive,tagcloud,links,weibo,douban


#### RSS 
rss: /atom.xml ## RSS address.

#### Image
imglogo:
  enable: false             ## display image logo true/false.
  src: img/author.jpg        ## `.svg` and `.png` are recommended,please put image into the theme folder `/jacman/source/img`.
favicon: img/yan.ico   ## size:32px*32px,`.ico` is recommended,please put image into the theme folder `/jacman/source/img`.     
rss_img: img/rss.png ## size:1920px*200px+. Banner Picture

### Theme Color 
theme_color:
    theme: '#2ca6cb'    ##the defaut theme color is blue

#### index post is expanding or not 
index:
  expand: true           ## default is unexpanding,so you can only see the short description of each post.
  excerpt_link: 继续阅读»  
  


#### Toc
toc:
  article: false   ## show contents in article.
  aside: false     ## show contents in aside.
## you can set both of the value to true of neither of them.
## if you don't want display contents in a specified post,you can modify `front-matter` and add `toc: false`.

#### Links
links:
  土木坛子: https://tumutanzi.com
  勺子歪歪: https://chenghouwen.com/
  路易大叔: http://louishan.com/
  博客大全: http://bkdq.org/
  尚磊博客: http://shanglei.net/
  BlogWeGo: http://blogwego.com/
  戴睿可: http://cn.derekyang.us/
  阮一峰: http://www.ruanyifeng.com/blog/
  兔二爷: https://too2ye.com/
  王语双: http://wys.me/
  宗志远: http://blog.sciencenet.cn/u/jiangnanlong
  毕业生: http://todayby.com/
  破襪子: http://pewae.com/


  

#### Comment
disqus_shortname:  ## e.g. wuchong   your disqus short name.
duoshuo_shortname: drunkevil

#### Share button
jiathis:
  enable: true ## if you use jiathis as your share tool,the built-in share tool won't be display.
  id:    ## e.g. 1889330 your jiathis ID. 
  tsina: ## e.g. 2176287895 Your weibo id,It will be used in share button.
  
#### Analytics
google_analytics:
  enable: true
  id: UA-59108758-1      ## e.g. UA-46321946-2 your google analytics ID.
  site: drunkevil.com     ## e.g. wuchong.me your google analytics site or set the value as auto.
## You MUST upgrade to Universal Analytics first!
## https://developers.google.com/analytics/devguides/collection/upgrade/?hl=zh_CN

#### Miscellaneous
ShowCustomFont: true  ## you can change custom font in `variable.styl` and `font.styl` which in the theme folder `/jacman/source/css`.
fancybox: true        ## if you use gallery post or want use fancybox please set the value to true.
totop: true           ## if you want to scroll to top in every post set the value to true


#### Custom Search
##google_cse: 
##  enable: false
##  cx:   005137013325984881798:adjgybi_m7w ## e.g. 005137013325984881798:adjgybi_m7w your Custom Search ID.
## https://www.google.com/cse/ 
## To enable the custom search You must create a "search" folder in '/source' and a "index.md" file
## set the 'front-matter' as
## layout: search 
## title: search
## ---
##baidu_search:     ## http://zn.baidu.com/
##  enable: false
##  id: 6412353765991038314   ## e.g. "783281470518440642"  for your baidu search id
##  site: http://zhannei.baidu.com/cse/search  ## your can change to your site instead of the default site
  
swift_search:
  enable: true
